$(document).ready(function(){
  $("button#show_airtable").click(function(){
      $("#airtable_actress").show();
  });
});
$(document).ready(function(){
  $("button#hide_airtable").click(function(){
      $("#airtable_actress").hide();
  });
});